export enum HealthFacilityType {
    RUMAHSAKIT = "RUMAH SAKIT",
    PUSKESMAS = "PUSKESMAS",
    KLINIK = "KLINIK",
    PRAKTIKDOKTER = "PRAKTIK DOKTER",
    APOTEK = "APOTEK",
    LABORATORIUM = "LABORATORIUM",
}